# Generated by Django 4.1.2 on 2022-10-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words_game", "0002_room_alter_word_word_word_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="room_name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
