# Generated by Django 4.1.2 on 2022-10-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words_game", "0003_room_room_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="room_name",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
