# Generated by Django 4.1.2 on 2022-10-22 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words_game", "0004_alter_room_room_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="words",
                to="words_game.room",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="word",
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
