# Generated by Django 4.1.2 on 2022-10-22 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words_game", "0005_alter_word_room_alter_word_word"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="room",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="words", to="words_game.room"
            ),
        ),
    ]
