# Generated by Django 4.1.2 on 2022-10-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words_game", "0007_alter_word_word_alter_word_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="host",
        ),
        migrations.AddField(
            model_name="room",
            name="password",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
